export enum MovieType {
	ACTION = 'ACTION',
	ADVENTURE = 'ADVENTURE',
	COMEDY = 'COMEDY',
	CRIME = 'CRIME',
	SPORTS = 'SPORTS',
	THRILLER = 'THRILLER',
	CARTOON = 'CARTOON',
	HORROR = 'HORROR',
	HISTORICAL = 'HISTORICAL'
}

export enum MovieStatus {
	ACTIVE = 'ACTIVE',
	PROCCESS = 'PROCCESS',
	DELETE = 'DELETE',
}

export enum MovieCountry {
	AMERICAN = 'AMERICAN',
	INDIAN = 'INDIAN',
	TURKISH = 'TURKISH',
	KOREAN = 'KOREAN',
	OTHER = 'OTHER'

}
